[package]
name = "getifs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/al8n/getifs"
homepage = "https://github.com/al8n/getifs"
documentation = "https://docs.rs/getifs"
description = "Yet another crate to get network interfaces information (including MTU)"
license = "MIT OR Apache-2.0"
rust-version = "1.73"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = []
serde = ["dep:serde"]

[dependencies]
bitflags = "2"
smol_str = "0.3"
smallvec-wrapper = "0.2"
ipnet = "2"

serde = { version = "1", features = ["derive"], optional = true }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
either = "1"
netlink-sys = "0.8"
netlink-packet-route = "0.21"
netlink-packet-core = "0.7"
netlink-packet-utils = "0.5"


[dev-dependencies]
criterion = "0.5"
tempfile = "3"


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
rust_2018_idioms = "warn"
single_use_lifetimes = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(all_tests)'] }
